<a href="https://colab.research.google.com/github/hwas2/Python_study/blob/master/14%EC%9D%BC%EC%B0%A8(colab).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 인덱스 활용
특정 열을 행 인덱스로 설정
- set_index() 함수를 사용하여 데이터프레임의 특정 열을 행 인덱스로 설정

특정 열을 행 인덱스로 설정하는 예제

In [ ]:
import pandas as pd

exam_data={'이름':['린하','인서','광열'],
           '국어':[70,90,80],'수학':[90,85,80],'영어':[100,80,90],'음악':[70,90,100]}
df=pd.DataFrame(exam_data)
print(df)

   이름  국어  수학   영어   음악
0  린하  70  90  100   70
1  인서  90  85   80   90
2  광열  80  80   90  100


In [ ]:
#특정 열을 데이터프레임의 행 인덱스로 설정
ndf=df.set_index('이름')
print(ndf)

    국어  수학   영어   음악
이름                  
린하  70  90  100   70
인서  90  85   80   90
광열  80  80   90  100


In [ ]:
#특정 열을 데이터프레임의 행 인덱스로 설정
ndf2=ndf.set_index('음악')
print(ndf2)

     국어  수학   영어
음악              
70   70  90  100
90   90  85   80
100  80  80   90


- 기존 "이름"행 인덱스는 제거가 된 것으로 확인

In [ ]:
#행 인덱스를 리셋
ndf3=ndf2.reset_index('음악')
print(ndf3)

    음악  국어  수학   영어
0   70  70  90  100
1   90  90  85   80
2  100  80  80   90


- 행 인덱스를 리셋해주어도 전에 지정해놓았던 행 인덱스가 다시 적용되지는 않음

In [ ]:
#특정 열 2개를 데이터프레임의 행 인덱스로 설정
ndf4=ndf.set_index(['수학','영어'])
print(ndf4)

        국어   음악
수학 영어          
90 100  70   70
85 80   90   90
80 90   80  100


- 두 개의 열을 행 인덱스로 지정 가능

행 인덱스 재배열
- reindex() 함수를 사용하여 데이터프레임의 행 인덱스를 새로운 배열로 재지정 가능
<code> 새로운 배열로 행 인덱스 재지정 : DataFrame 객체.reindex()</code><br><br>
- 기존 데이터프레임에 존재하지 않는 행 인덱스가 새로 추가되는 경우 해당 행의 데이터 값은 NaN값이 입력됨

새로운 배열로 행 인덱스 재지정 예제

In [ ]:
#판다스 import
import pandas as pd

#key:value를 쌍으로 갖는 딕셔너리를 생성, 변수 dict_data에 저장
dict_data={'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

#판다스 DataFrame() 함수로 딕셔너리를 데이터프레임로 변환, 변수 df에 저장
df=pd.DataFrame(dict_data, index=['r0','r1','r2'])

print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15


In [ ]:
#행 인덱스 재배열로 사용될 변수를 지정
new_index=['r0','r1']
new_index2=['r3','r4','r5']
new_index3=['r0','r1','r2','r3','r4']

#행 인덱스를 ['r0','r1']로 재지정
ndf=df.reindex(new_index)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14


In [ ]:
#행 인덱스를 ['r3','r4','r5']로 재지정
ndf2=df.reindex(new_index2)
print(ndf2)

    c0  c1  c2  c3  c4
r3 NaN NaN NaN NaN NaN
r4 NaN NaN NaN NaN NaN
r5 NaN NaN NaN NaN NaN


- 새로운 행 인덱스로 재지정 할 경우 원소 값이 없으므로 NAN이 표기됨

In [ ]:
#행 인덱스를 ['r0','r1','r2','r3','r4']로 재지정
ndf3=df.reindex(new_index3)
print(ndf3)

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN


In [ ]:
#열 순서 변경
#columns 옵션 사용
ndf4=ndf3.reindex(columns=['c2','c1','c4','c0','c3'])
print(ndf4)

     c2   c1    c4   c0    c3
r0  7.0  4.0  13.0  1.0  10.0
r1  8.0  5.0  14.0  2.0  11.0
r2  9.0  6.0  15.0  3.0  12.0
r3  NaN  NaN   NaN  NaN   NaN
r4  NaN  NaN   NaN  NaN   NaN


행 인덱스 초기화
- reset_index() 함수를 활용하여 행 인덱스를 정수형 위치 인덱스로 초기화(기존 행 인덱스는 열로 이동)<br>
<code>정수형 위치 인덱스로 초기화: DataFrame 객체.reset_index()

행 인덱스를 정수형 위치 인덱스로 초기화하는 예제

In [ ]:
#판다스 import
import pandas as pd

#key:value를 쌍으로 갖는 딕셔너리를 생성, 변수 dict_data에 저장
dict_data={'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

#판다스 DataFrame() 함수로 딕셔너리를 데이터프레임로 변환, 변수 df에 저장
df=pd.DataFrame(dict_data, index=['r0','r1','r2'])

print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15


In [ ]:
#행 인덱스를 정수형으로 초기화
ndf=df.reset_index()
print(ndf)

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15


In [ ]:
ndf2=ndf.set_index('index')
print(ndf2)

       c0  c1  c2  c3  c4
index                    
r0      1   4   7  10  13
r1      2   5   8  11  14
r2      3   6   9  12  15


행 인덱스를 기준으로 데이터 프레임 정렬

In [ ]:
#판다스 import
import pandas as pd

#key:value를 쌍으로 갖는 딕셔너리를 생성, 변수 dict_data에 저장
dict_data={'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

#판다스 DataFrame() 함수로 딕셔너리를 데이터프레임로 변환, 변수 df에 저장
df=pd.DataFrame(dict_data, index=['r0','r1','r2'])

print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15


In [ ]:
#내림차순으로 행 인덱스 정렬
ndf=df.sort_index(ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13


In [ ]:
#오름차순으로 행 인덱스 정렬
ndf2=ndf.sort_index() #ascending=True
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15


행 인덱스를 기준으로 데이터 프레임 정렬
- sort_index() 함수를 사용하여 행 인덱스를 기준으로 데이터프레임의 값을 정렬
 - ascending 옵션을 사용하여 오름차순 혹은 내림차순으로 설정<br>
True : 오름차순 정렬<br>
False : 내림차순 정렬<br>
 <code> 행 인덱스 기준 정렬 : DataFrame 객체.sort_index()</code>

열 기준 정렬 예제

In [ ]:
#c1 열을 기준으로 내림차순 정렬
ndf=df.sort_values(by='c1',ascending=False)
print(ndf)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13


In [ ]:
#c1 열을 기준으로 오름차순 정렬
ndf2=df.sort_values(by='c1',ascending=True)
print(ndf2)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15


많은 열 중에 두 개의 특정 열의 위치를 바꾸고 싶은 경우?<br>
1. reindex로 새로운 열 배열이 지정된 데이터프레임을 생성
2. 바뀐 데이터프레임과 나눠진 기존 데이터프레임을 결합(concat 사용)

# 외부 파일 읽어오기
- 판다스는 다양한 형태의 외부 파일을 읽어와 데이터프레임으로 변환하는 함수를 제공
- 어떤 파일이든 판다스 객체인 데이터프레임으로 변환되면 판다스의 모든 함수와 기능을 자유롭게 사용 가능
- 데이터 프레임을 다양한 유형의 파일로 저장 가능
 - CSV, JSON, HTML, MS Excel, SQL, ...

## CSV 파일
- comma-separated values 의 약자
 - 데이터 값을 쉼표(,)로 구분하고 있다는 의미를 가진 파일
- CSV 파일을 -> 데이터프레임<br>
<code> pandas.read_csv("파일 경로(이름).csv")</code>

CSV 파일 읽기 예제 (read_test.csv파일 Pyrhon폴더에 저장)

In [ ]:
import pandas as pd

#파일 경로를 찾고, 변수 file_path에 저장
file_path='./read_test.csv'

In [ ]:
#read_csv() 함수로 데이터프레임 변환, 변수 df1에 저장
df1=pd.read_csv(file_path)
print(df1)

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9


In [ ]:
#read_csv() 함수로 데이터프레임 변환, 변수 df2에 저장, header=None 옵션 사용
df2=pd.read_csv(file_path, header=None)
print(df2)

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9


In [ ]:
#read_csv() 함수로 데이터프레임 변환, 변수 df3에 저장, index_col=None 옵션 사용
df3=pd.read_csv(file_path, index_col=None)
print(df3)

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9


In [ ]:
#read_csv() 함수로 데이터프레임 변환, 변수 df4에 저장, index_col='c0' 옵션 사용
df4=pd.read_csv(file_path, index_col='c0')
print(df4)

    c1  c2  c3
c0            
0    1   4   7
1    2   5   8
2    3   6   9


## Excel 파일
- Excel 파일(확장자.xlsx)의 행과 열은 데이터프레임의 행, 열로 일대일 대응
- Excel 파일 -> 데이터프레임<br>
<code> pandas.read_excel("파일 경로(이름).xlsx")</code>

파일명 : 남북한발전전력량.xlsx<br>
자료 출처 : KOSIS(통계청), 2021.09.30

In [ ]:
!pip install openpyxl

     -------------------------------------- 242.2/242.2 KB 4.9 MB/s eta 0:00:00


In [ ]:
import pandas as pd

#read_excel() 함수로 데이터프레임 변환
df1=pd.read_excel('./남북한발전전력량.xlsx', engine='openpyxl')
df2=pd.read_excel('./남북한발전전력량.xlsx', header=None)

- xlsx 파일을 읽어오지 못할 경우 read_exce()함수 옵션으로 engine='openpyxl'사용
 - df1=pd.read_excel('./남북한발전전력량.xlsx', engine='openpyxl')

In [ ]:
df1

전력량 (억㎾h) 발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...  2007  \
0        남한     합계  1077  1186  1310  1444  1650  1847  2055  2244  ...  4031   
1       NaN     수력    64    51    49    60    41    55    52    54  ...    50   
2       NaN     화력   484   573   696   803  1022  1122  1264  1420  ...  2551   
3       NaN    원자력   529   563   565   581   587   670   739   771  ...  1429   
4       NaN    신재생     -     -     -     -     -     -     -     -  ...     -   
5        북한     합계   277   263   247   221   231   230   213   193  ...   236   
6       NaN     수력   156   150   142   133   138   142   125   107  ...   133   
7       NaN     화력   121   113   105    88    93    88    88    86  ...   103   
8       NaN    원자력     -     -     -     -     -     -     -     -  ...     -   

   2008  2009  2010  2011  2012  2013  2014  2015  2016  
0  4224  4336  4747  4969  5096  5171  5220  5281  5404  
1    56    56    65    78    77    84    78    58    66  
2  2658  2802  3196  3343  3430  3581  3427  3402  3523  
3  1510  1478  1486  1547  1503  1388  1564  1648  1620  
4     -     -     -     -    86   118   151   173   195  
5   255   235   237   211   215   221   216   190   239  
6   141   125   134   132   135   139   130   100   128  
7   114   110   103    79    80    82    86    90   111  
8     -     -     -     -     -     -     -     -     -  

[9 rows x 29 columns]

In [ ]:
df2

0       1     2     3     4     5     6     7     8     9   ...  \
0  전력량 (억㎾h)  발전 전력별  1990  1991  1992  1993  1994  1995  1996  1997  ...   
1         남한      합계  1077  1186  1310  1444  1650  1847  2055  2244  ...   
2        NaN      수력    64    51    49    60    41    55    52    54  ...   
3        NaN      화력   484   573   696   803  1022  1122  1264  1420  ...   
4        NaN     원자력   529   563   565   581   587   670   739   771  ...   
5        NaN     신재생     -     -     -     -     -     -     -     -  ...   
6         북한      합계   277   263   247   221   231   230   213   193  ...   
7        NaN      수력   156   150   142   133   138   142   125   107  ...   
8        NaN      화력   121   113   105    88    93    88    88    86  ...   
9        NaN     원자력     -     -     -     -     -     -     -     -  ...   

     19    20    21    22    23    24    25    26    27    28  
0  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  
1  4031  4224  4336  4747  4969  5096  5171  5220  5281  5404  
2    50    56    56    65    78    77    84    78    58    66  
3  2551  2658  2802  3196  3343  3430  3581  3427  3402  3523  
4  1429  1510  1478  1486  1547  1503  1388  1564  1648  1620  
5     -     -     -     -     -    86   118   151   173   195  
6   236   255   235   237   211   215   221   216   190   239  
7   133   141   125   134   132   135   139   130   100   128  
8   103   114   110   103    79    80    82    86    90   111  
9     -     -     -     -     -     -     -     -     -     -  

[10 rows x 29 columns]

read_test.json

## jSON 파일
- JSON 파일(확장자 .json)은 데이터 공유 목적으로 개발된 특수한 파일 형식
- 파이썬 딕셔너리와 비슷하게 'key:value' 구조를 가짐<br>
<code> pandas.read_json("파일 경로(이름).json")</code>

In [ ]:
import pandas as pd

#read_json() 함수로 데이터프레임 변환
df=pd.read_json('./read_test.json')

print(df)

ValueError: ignored

--------------------------------------------------

# NUMPY
- Numerical Python
-  산술 계산을 위한 패키지
 - 다차원 배열인 ndarray는 빠른 배열 계산을 제공
 - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
 - 선형대수, 난수 생성기, 푸리에 변환 가능
- 일반적인 산술 데이터 처리를 위한 기본 라이브러리를 제공
 - 연산 처리 후 통계나 분석데이터를 처리하기 위해선 Pandas를 사용
- 파이썬 산술 계산 영역에서 중요한 위치를 차지하는 이유 중 하나는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되어 있기 때문

Numpy 사용 예제<br>
- 1차원 배열 생성

In [ ]:
import numpy as np

my_arr=np.arange(100)
my_list=list(range(100))

print(type(my_arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
print(my_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


Numpy와 list의 연산 속도 비교 예제<br<
- 속도 차이가 나보이지 않으나 배열 연산이 더 빠름

In [ ]:
my_arr=np.arange(100000)
my_list=list(range(100000))

%time
for i in range(10000):
    my_arr2=my_arr*2

CPU times: total: 0 ns
Wall time: 0 ns


In [ ]:
%time
for i in range(10000):
    my_list2=[i*2 for j in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


다차원 배열 객체
- Numpy는 ndarray라고 하는 N차원 배열 객체를 사용
 - 1차원 : Vectors
 - 2차원 : Matrices
 - 3차원 : Tensors

2 x 3 배열을 랜덤 생성(가우시안 분포 사용)

In [ ]:
data=np.random.randn(2,3)
print(data)

[[ 0.10317849  1.22297984  0.5019469 ]
 [ 0.30116702  2.6762899  -1.15309715]]


ndarray 생성하기 예제(list->array)

In [ ]:
data1=[5,7,8,1,4]
type(data1)

list

In [ ]:
arr1=np.array(data1)
type(arr1)

numpy.ndarray

In [ ]:
print(arr1)

[5 7 8 1 4]


2차원 배열 생성 예제

In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


numpy 배열의 산술 연산
- numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할 수 있음
 - "벡터화"라고 부름

In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6]])
#요소곱
print(arr1*arr1)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
#요소합
print(arr1+arr1)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#나눗셈
print(1/arr1)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [ ]:
print(arr1==arr1)

[[ True  True  True]
 [ True  True  True]]


In [ ]:
#행렬곱
print(np.dot(arr1, np.transpose(arr1)))

[[14 32]
 [32 77]]


3 x 3 배열 생성(범위 지정 후 모양을 다듬어서 생성)

In [ ]:
#1차원 배열 생성
arr1= np.array(range(1,10))
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원 3 x 3 배열 생성
arr2= np.array(range(1,10)).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


배열 인덱싱과 슬라이싱
- numpy 배열은 순차적(sequential) 데이터이기 때문에 인덱싱과 슬라이싱 가능

배열 인덱싱 예제

In [ ]:
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr1[5])
print(arr1[5:8])

5
[5 6 7]


다차원 배열 객체 연산
- 브로드캐스팅되어 연산됨

In [ ]:
# 1 x 3 배열 +정수
print(np.arange(3)+5)

#3 x 3 배열 + 1 x 3 배열
print(np.ones((3,3)) + np.arange(3))

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
#3 x 1 배열 + 1 x 3 배열
print(np.arange(3).reshape(3,1)+np.arange(3))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


배열 전치와 축 바꾸기
- np.transpose() or np.T 사용

In [ ]:
arr=np.arange(3)
print(type(arr))
print(arr.transpose())

arr2=np.array([0,1,2])
print(type(arr2))
print(arr2.transpose())

<class 'numpy.ndarray'>
[0 1 2]
<class 'numpy.ndarray'>
[0 1 2]


In [ ]:
arr=np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print(arr.transpose())

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


np.trasnpose(np.array([[0,1,2]]))
- 2차원 배열이기 때문에 전치와 축 바꾸기 가능

np.trasnpose(np.arange(3),type(np.arange(3)))
- 1차원 배열은 전치와 축 바꾸기 불가능

3차원 배열 만들기

In [ ]:
arr=np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
             [15,16,17,18],
             [19,20,21,22]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


단항 유니버설 함수, 이항 유니버설 함수, 수학 메서드, 통계 메서드, 집합 관련 함수, 배열 데이터 파일 입출력,...

numpy 배열을 pandas dataframe으로 바꾸는 방법

In [ ]:
arr=np.arange(15).reshape(3,5)

import pandas as pd

df=pd.DataFrame(arr)
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14


Numpy를 어디서 쓰는가<br>
이미지 처리할 때 numpy 사용
사진(픽셀)-> 행렬 처리

3차원 배열 데이터프레임으로 변환 참고<br>
https://velog.io/@autumn/Python-AttributeError-module-pandas-has-no-attribute-Panel

---------------------------------------

# 산술 연산
- 판다스 객체의 산술 연산 3단계 프로세스(내부)
1. 행/열 인덱스를 기준으로 모든 원소를 정렬
2. 일대일 대응되는 원소끼리 연산
3. 대응되는 원소가 없다면 NaN

## 시리즈 연산
시리즈 vs 연산
- 시리즈 객체에 연산을 하면 계산된 결과를 시리즈 객체로 반환<br>
<code>시리즈와 숫자 연산:Series객체 + 연산자(+,-,*,/)+숫자</code>

시리즈를 숫자로 나누기 예제

In [ ]:
import pandas as pd

#딕셔너리 데이터로 판다스 시리즈 만들기
student1=pd.Series({'국어':100,'영어':80,'수학':90})
print(student1)

국어    100
영어     80
수학     90
dtype: int64


In [ ]:
#학생의 과목별 점수를 100으로 나누기
percentage=student1/100
print(percentage)

국어    1.0
영어    0.8
수학    0.9
dtype: float64


시리즈 vs 시리즈<br>
<code>시리즈와 시리즈 연산:Series객체1 + 연산자(+,-,*,/)+Series객체2</code>

시리즈 사칙연산 예제

- 시리즈의 인덱스에 해당하는 부분이 데이터프레임의 옆 자리에 오게 됨

In [ ]:
import pandas as pd

#딕셔너리 데이터로 판다스 시리즈 만들기
student1=pd.Series({'국어':100,'영어':80,'수학':90})
student2=pd.Series({'국어':80,'영어':90,'수학':80})

#두 학생의 과목별 점수로 사칙연산 수행
addition=student1+student2
subtraction=student1-student2
multiplication=student1*student2
division=student1/student2

#사칙연산 결과를 데이터프레임으로 합치기(시리즈-> 데이터프레임)
result=pd.DataFrame([addition,subtraction,multiplication,division],
                    index=['덧셈','뺄셈','곱셈','나눗셈'])

In [ ]:
print(student1)

국어    100
영어     80
수학     90
dtype: int64


In [ ]:
print(student2)

국어    80
영어    90
수학    80
dtype: int64


In [ ]:
print(result)

          국어           영어        수학
덧셈    180.00   170.000000   170.000
뺄셈     20.00   -10.000000    10.000
곱셈   8000.00  7200.000000  7200.000
나눗셈     1.25     0.888889     1.125


In [ ]:
import pandas as pd

#딕셔너리 데이터로 판다스 시리즈 만들기
student1=pd.Series({'국어':np.nan,'영어':80,'수학':90})
student2=pd.Series({'수학':80,'국어':80})

#두 학생의 과목별 점수로 사칙연산 수행
addition=student1+student2
subtraction=student1-student2
multiplication=student1*student2
division=student1/student2

#사칙연산 결과를 데이터프레임으로 합치기(시리즈-> 데이터프레임)
result=pd.DataFrame([addition,subtraction,multiplication,division],
                    index=['덧셈','뺄셈','곱셈','나눗셈'])

In [ ]:
print(student1)

국어     NaN
영어    80.0
수학    90.0
dtype: float64


In [ ]:
print(student2)

수학    80
국어    80
dtype: int64


In [ ]:
print(result)

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN


연산 메소드
- 연산 결과가 NaN으로 반환되지 않도록 하기 위해 연산 메소드에 fill_value 옵션을 설정하여 적용<br>
<code>연산 메소드 사용(시리즈와 시리즈 덧셈):Series 객체1.add(Series 객체2, fill_value=0)

연산 메소드 사용 예제(시리즈 연산)

In [ ]:
import pandas as pd

#딕셔너리 데이터로 판다스 시리즈 만들기
student1=pd.Series({'국어':np.nan,'영어':80,'수학':90})
student2=pd.Series({'수학':80,'국어':80})

#두 학생의 과목별 점수로 사칙연산 수행
sr_add=student1.add(student2,fill_value=0)
sr_sub=student1.sub(student2,fill_value=0)
sr_mul=student1.mul(student2,fill_value=0)
sr_div=student1.div(student2,fill_value=0)

#사칙연산 결과를 데이터프레임으로 합치지(시리즈-> 데이터프레임)
result=pd.DataFrame([sr_add,sr_sub,sr_mul,sr_div],
                    index=['덧셈','뺄셈','곱셈','나눗셈'])

In [ ]:
print(result)

       국어        수학    영어
덧셈   80.0   170.000  80.0
뺄셈  -80.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf


- '영어'열의 나눗셈 값은 80을 0으로 나누었기 때문에 무한대로 표기(inf)

## 데이터프레임 연산
- 데이터프레임은 여러 시리즈 한데 모인 것
- 행/열 인덱스를 정렬하고 일대일 대응되는 원소끼리 연산 처리

데이터프레임 vs 숫자<br>
<code>데이터프레임과 숫자 연산:DataFrame 객체+연산자(+,-,*,/)+숫자</code>

해결 위해 사용해본 방법<br>


!pip install seaborn<br>


import pip<br>
pip.main(['install', 'seaborn'])<br>


cmd창 C:\Users\OOO>python -m pip install seaborn<br>


%pip install seaborn<br>


import sys <br>
!{sys.executable} -m pip install seaborn<br>

pip 업데이트 cmd 관리자모드<br>
pip install --upgrade pip<br>
pip3 install seaborn</n>


cmd 관리자모드<br>
python -m pip install seaborn<br>


pip install pyforest<br>
python<br>
import seaborn as sns<br>


seaborn 폴더 python에 복사 후 경로 설정<br>
python<br>
import sys<br>
sys.path.append("seaborn폴더 경로")<br>
import seaborn<br>
안되면 sys.path.remove("경로")<br>

결국 colab사용하기로

In [ ]:
import sys
print(sys.version)

3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]


데이터프레임에 숫자 더하기 예제

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
# titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age', 'fare']]

# 첫 5행만 표시
print(df.head())

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


In [ ]:
#데이터프레임에 숫자 10 더하기
addition=df+10
print(addition.head())

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


데이터프레임 vs 데이터프레임<br>
- 각 데이터프레임의 같은 행, 같은 열 위치에 있는 원소끼리 계산
- 데이터프레임에서 어느 한 쪽에 원소가 존재하지 않거나 NaN이면 연산 결과로 NaN으로 처리됨<br>
<code>데이터프레임의 연산자 활용:DataFrame 객체1+연산자(+,-,*,/)+DataFrame객체2</code>

In [ ]:
import pandas as pd
import seaborn as sns

#titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','fare']]

#데이터프레임에 숫자 10 더하기
addition=df+10

#데이터프레임끼리 연산하기
subtraction=addition-df
print(subtraction.head())

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0


In [ ]:
print(subtraction.tail())

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0


데이터프레임 연산에서 NaN 처리하기 예제 - 첫 번째 방법

In [ ]:
import pandas as pd
import seaborn as sns

#titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','fare']]

#데이터프레임에 숫자 10 더하기
addition=df+10 #NaN(0)+10

df_sub.ffill(inplace=True)
#ffill() 함수 사용시 이전 연산에 대한 결과값을 NaN대신 출력
print(df_sub.tail())

      age  fare
886  10.0  10.0
887  10.0  10.0
888  10.0  10.0
889  10.0  10.0
890  10.0  10.0


데이터프레임 연산예제 NaN 처리하기 예제 - 두번째 방법

In [ ]:
import pandas as pd
import seaborn as sns

#titanic 데이터셋에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','fare']]

#데이터프레임에 NaN을 0으로 바꾸기
df.fillna(0,inplace=True)

#데이터프레임에 숫자 10 더하기
addition=df+10

print(addition.tail())

      age   fare
886  37.0  23.00
887  29.0  40.00
888  10.0  33.45
889  36.0  40.00
890  42.0  17.75
